spring.application.name=infoarchive

# server port
server.port=${PORT:8082}
#server.port=8082

# Automatic Restart
spring.devtools.restart.enabled=false
#spring.devtools.restart.enabled=true

# Live Reload \uAE30\uB2A5 \uD65C\uC131\uD654
#spring.devtools.livereload.enabled=true
spring.devtools.livereload.enabled=false
# mariaDB
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:infoarchive;MODE=MariaDB;DATABASE_TO_UPPER=false;DB_CLOSE_DELAY=-1
spring.datasource.username=sa
spring.datasource.password=
#spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
#spring.datasource.url=jdbc:mariadb://192.168.0.169:3306/infoarchive
#spring.datasource.username=infoarchive
#spring.datasource.password=1234

# jpa
spring.jpa.hibernate.ddl-auto=create
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.show-sql=true
#spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

# data.sql / schema.sql ?? ?? ??
spring.sql.init.mode=never

#SQL log
#logging.level.org.hibernate.type.descriptor.sql=trace

#thymeleaf
spring.thymeleaf.cache=false

payment.mock=true

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB